### ISSUE TITLE
Teddy 3/22 AM Questions

### ISSUE THREAD

**Issue by zgulde** [CodeupClassroom/study-halls#3]
Ask your questions here! Code samples are allowed and encouraged!

**Comment by JamesFowler3** [comment]
Can we please go over Joins  and Sub-queries in mySQL?

**Comment by emmaldejong** [comment]
****FIXED!******
After I posted, Laura solved my issue! Here is our solution to below:
`SELECT Continent, AVG(LifeExpectancy) AS Life_Expectancy
FROM country
GROUP BY Continent
ORDER BY AVG(LifeExpectancy);`

`SELECT Region, AVG(LifeExpectancy) AS Life_Expectancy
FROM country
GROUP BY Region
ORDER BY Life_Expectancy;`

How would I short the following code from **"shortest to longest"**? This is from the world database in the MySQL Further Reading.

`SELECT Continent, AVG(LifeExpectancy) AS Life_Expectancy
FROM country
GROUP BY Continent;`

`SELECT Region, AVG(LifeExpectancy) AS Life_Expectancy
FROM country
GROUP BY Region;`

<img width="645" alt="screen shot 2018-03-21 at 3 14 06 pm" src="https://user-images.githubusercontent.com/35229956/37734917-8d2108ea-2d1a-11e8-8aef-a4d8b6013614.png">

**Comment by emmaldejong** [comment]
Can we review when to use subqueries v. when to use joins? How will we know when to use subqueries? Besides syntax, what are the differences between the two?
