### ISSUE TITLE
Teddy 2018-04-05 questions

### ISSUE THREAD

**Issue by zgulde** [CodeupClassroom/study-halls#7]
Topics we've covered in java iii:

- Dependencies (maven + `pom.xml`)
- Servlets
- JSP and JSTL
- MVC
- Sessions and Cookies
- JDBC
- User Input
- Passwords

**Comment by lalepro** [comment]
I think my misunderstanding of the mvc is when things get complex like the servlet lingo, and wiring everything together. I really want to get it, just need more time. Whats the difference between statements and prepared statements
